/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.geom.Borracha;
import gui.geom.Caneta;
import gui.geom.Elipse;
import gui.geom.Forma;
import gui.geom.Linha;
import gui.geom.Poligono;
import gui.geom.Retangulo;
import java.awt.Color;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.JSpinner;
import javax.swing.KeyStroke;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger( JanelaPrincipal.class.getName() );
    
    private JSpinner spnEspessura;
    private JSlider sldEspessura;
    
    private PainelDesenho painelDesenho; 
    
    private Forma novaForma;
    private int quantidadeLados;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        quantidadeLados = 3;
                     
        btnCaneta.setIcon(carregarIcone("/gui/img/caneta.png", 20, 20));
        btnBorracha.setIcon(carregarIcone("/gui/img/borracha.png", 20, 20));
        btnUndo.setIcon(carregarIcone("/gui/img/seta-esquerda.png", 20, 20));
        btnRedo.setIcon(carregarIcone("/gui/img/seta-direita.png", 20, 20));
        
        JComponent rootPane = this.getRootPane();
        
        rootPane.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_Z, InputEvent.CTRL_DOWN_MASK),
            "undoAction"
        );
        rootPane.getActionMap().put("undoAction", new AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                painelDesenho.undo();
            }
        });
        
        rootPane.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_Y, InputEvent.CTRL_DOWN_MASK),
            "redoAction"
        );
        rootPane.getActionMap().put("redoAction", new AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                painelDesenho.redo();
            }
        });
        
        sldEspessura = new JSlider(1, 50, 5);
        sldEspessura.setToolTipText("Ajustar espessura do traço");
        
        painelFerramentas.add(new JLabel("Espessura:"));
        painelFerramentas.add(sldEspessura);
        painelFerramentas.revalidate();
        
        painelFerramentas.revalidate();
        
        painelDesenho = new PainelDesenho();
    
        painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenhoMousePressed(evt);
            }
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseReleased(evt);
            }
        });

        painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenhoMouseDragged(evt);
            }
        });

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(painelFerramentas, java.awt.BorderLayout.NORTH);
        getContentPane().add(painelDesenho, java.awt.BorderLayout.CENTER);
    }
    
    private ImageIcon carregarIcone(String caminho, int largura, int altura) {
        try{
            java.net.URL url = getClass().getResource(caminho);
            if(url != null) {
                javax.swing.ImageIcon iconeOriginal = new javax.swing.ImageIcon(url);
                java.awt.Image imagemRedimensionada = iconeOriginal.getImage()
                        .getScaledInstance(largura, altura, java.awt.Image.SCALE_SMOOTH);
                return new javax.swing.ImageIcon(imagemRedimensionada);
            }
        } catch(Exception e) {
            
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFerramentas = new javax.swing.ButtonGroup();
        painelFerramentas = new javax.swing.JPanel();
        btnLinha = new javax.swing.JToggleButton();
        btnRetangulo = new javax.swing.JToggleButton();
        btnElipse = new javax.swing.JToggleButton();
        btnPoligono = new javax.swing.JToggleButton();
        btnCaneta = new javax.swing.JToggleButton();
        painelCorContorno = new javax.swing.JPanel();
        painelCorPreenchimento = new javax.swing.JPanel();
        btnUndo = new javax.swing.JToggleButton();
        btnRedo = new javax.swing.JToggleButton();
        btnBorracha = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Paint");

        btnGroupFerramentas.add(btnLinha);
        btnLinha.setSelected(true);
        btnLinha.setText("Linha");
        btnLinha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLinha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnRetangulo);
        btnRetangulo.setText("Retângulo");
        btnRetangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnElipse);
        btnElipse.setText("Elipse");
        btnElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnGroupFerramentas.add(btnPoligono);
        btnPoligono.setText("Polígono");
        btnPoligono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPoligono.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPoligono.addActionListener(this::btnPoligonoActionPerformed);

        btnGroupFerramentas.add(btnCaneta);
        btnCaneta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaneta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaneta.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnCanetaMouseDragged(evt);
            }
        });
        btnCaneta.addActionListener(this::btnCanetaActionPerformed);

        painelCorContorno.setBackground(new java.awt.Color(0, 0, 0));
        painelCorContorno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCorContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelCorContorno.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorContorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorContornoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorContornoLayout = new javax.swing.GroupLayout(painelCorContorno);
        painelCorContorno.setLayout(painelCorContornoLayout);
        painelCorContornoLayout.setHorizontalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelCorContornoLayout.setVerticalGroup(
            painelCorContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        painelCorPreenchimento.setBackground(new java.awt.Color(255, 255, 255));
        painelCorPreenchimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelCorPreenchimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painelCorPreenchimento.setPreferredSize(new java.awt.Dimension(20, 20));
        painelCorPreenchimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelCorPreenchimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCorPreenchimentoLayout = new javax.swing.GroupLayout(painelCorPreenchimento);
        painelCorPreenchimento.setLayout(painelCorPreenchimentoLayout);
        painelCorPreenchimentoLayout.setHorizontalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        painelCorPreenchimentoLayout.setVerticalGroup(
            painelCorPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        btnGroupFerramentas.add(btnUndo);
        btnUndo.addActionListener(this::btnUndoActionPerformed);

        btnGroupFerramentas.add(btnRedo);
        btnRedo.addActionListener(this::btnRedoActionPerformed);

        btnGroupFerramentas.add(btnBorracha);
        btnBorracha.addActionListener(this::btnBorrachaActionPerformed);

        javax.swing.GroupLayout painelFerramentasLayout = new javax.swing.GroupLayout(painelFerramentas);
        painelFerramentas.setLayout(painelFerramentasLayout);
        painelFerramentasLayout.setHorizontalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLinha)
                .addGap(0, 0, 0)
                .addComponent(btnRetangulo)
                .addGap(0, 0, 0)
                .addComponent(btnElipse)
                .addGap(0, 0, 0)
                .addComponent(btnPoligono)
                .addGap(0, 0, 0)
                .addComponent(btnCaneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorracha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUndo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedo)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        painelFerramentasLayout.setVerticalGroup(
            painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelCorContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelCorPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorracha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 269, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
        int espessura = sldEspessura.getValue();
        
        if ( btnLinha.isSelected() ) {
            novaForma = new Linha();
        } else if ( btnRetangulo.isSelected() ) {
            novaForma = new Retangulo();
        } else if ( btnElipse.isSelected() ) {
            novaForma = new Elipse();
        } else if ( btnPoligono.isSelected() ) {
            novaForma = new Poligono( quantidadeLados );
        } else if (btnCaneta.isSelected()){
            novaForma = new Caneta(espessura);
        } else if ( btnBorracha.isSelected() ) {
            novaForma = new Borracha(espessura);      
        } else {
            novaForma = new Linha();
        }
        
        novaForma.setIniX( evt.getX() );
        novaForma.setIniY( evt.getY() );
        novaForma.setFimX( evt.getX() );
        novaForma.setFimY( evt.getY() );
        
        if(novaForma instanceof Borracha) {
            novaForma.setCorContorno( Color.WHITE );
        } else {
            novaForma.setCorContorno( painelCorContorno.getBackground() );
        }
        
        novaForma.setCorPreenchimento( painelCorPreenchimento.getBackground() );
    
        if(novaForma instanceof Caneta) {
            ((Caneta) novaForma).adicionarPonto( evt.getX(), evt.getY() );
        }
        
        if(novaForma instanceof Caneta) {
            ((Caneta) novaForma).adicionarPonto( evt.getX(), evt.getY() );
        }
        
        painelDesenho.adicionarForma( novaForma );
        painelDesenho.repaint();
    }//GEN-LAST:event_painelDesenhoMousePressed

    private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
        novaForma.setFimX( evt.getX() );
        novaForma.setFimY( evt.getY() );
        painelDesenho.repaint();
    }//GEN-LAST:event_painelDesenhoMouseReleased

    private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
        novaForma.setFimX( evt.getX() );
        novaForma.setFimY( evt.getY() );
        painelDesenho.repaint();
        
        if( novaForma instanceof Caneta ) {
            ((Caneta) novaForma).adicionarPonto( evt.getX(), evt.getY() );
        } else {
            novaForma.setFimX( evt.getX() );
            novaForma.setFimY( evt.getY() );
        }
        painelDesenho.repaint();
    }//GEN-LAST:event_painelDesenhoMouseDragged

    private void painelCorContornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorContornoMouseClicked
        
        Color corSelecionada = JColorChooser.showDialog( 
                this, "Cor do Contorno", painelCorContorno.getBackground() );
        
        if ( corSelecionada != null ) {
            painelCorContorno.setBackground( corSelecionada );
        }
        
    }//GEN-LAST:event_painelCorContornoMouseClicked

    private void painelCorPreenchimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCorPreenchimentoMouseClicked
        
        Color corSelecionada = JColorChooser.showDialog( 
                this, "Cor do Preenchimento", painelCorPreenchimento.getBackground() );
        
        if ( corSelecionada != null ) {
            painelCorPreenchimento.setBackground( corSelecionada );
        }
        
    }//GEN-LAST:event_painelCorPreenchimentoMouseClicked

    private void btnPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonoActionPerformed
        
        try {
            String valor = JOptionPane.showInputDialog( "Quantidade de Lados:" );
            int quantidade = Integer.parseInt( valor );
            if ( quantidade >= 3 ) {
                quantidadeLados = quantidade;
            }
        } catch ( NumberFormatException exc ) {
            // erro
        }
        
    }//GEN-LAST:event_btnPoligonoActionPerformed
    
    private void btnCanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanetaActionPerformed
        try {
            String valor = JOptionPane.showInputDialog(this, "Espessura da Caneta (1 a 50):", sldEspessura.getValue());
            if(valor != null) {
                int espessura = Integer.parseInt(valor);
                if(espessura >= 1 && espessura <= 50) {
                    sldEspessura.setValue(espessura);
                } else {
                    JOptionPane.showMessageDialog(this, "Por favor, insira um valor entre 1 e 50.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch(NumberFormatException exc) {
            JOptionPane.showMessageDialog(this, "Digite apenas números inteiros.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCanetaActionPerformed

    private void btnCanetaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanetaMouseDragged
 
    }//GEN-LAST:event_btnCanetaMouseDragged

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        painelDesenho.undo();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        painelDesenho.redo();
    }//GEN-LAST:event_btnRedoActionPerformed

    private void btnBorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrachaActionPerformed
        try {
            String valor = JOptionPane.showInputDialog(this, "Tamanho da Borracha (1 a 50):", sldEspessura.getValue());
            if(valor != null) {
                int espessura = Integer.parseInt(valor);
                if(espessura >= 1 && espessura <= 50) {
                    sldEspessura.setValue(espessura);
                } else {
                    JOptionPane.showMessageDialog(this, "Por favor, insira um valor entre 1 e 50.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch(NumberFormatException exc) {
            JOptionPane.showMessageDialog(this, "Digite apenas números inteiros!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBorrachaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex ) {
            logger.log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( () -> new JanelaPrincipal().setVisible( true ) );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBorracha;
    private javax.swing.JToggleButton btnCaneta;
    private javax.swing.JToggleButton btnElipse;
    private javax.swing.ButtonGroup btnGroupFerramentas;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnPoligono;
    private javax.swing.JToggleButton btnRedo;
    private javax.swing.JToggleButton btnRetangulo;
    private javax.swing.JToggleButton btnUndo;
    private javax.swing.JPanel painelCorContorno;
    private javax.swing.JPanel painelCorPreenchimento;
    private javax.swing.JPanel painelFerramentas;
    // End of variables declaration//GEN-END:variables
}
